// export default function ResumeLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <div className="flex h-screen flex-col">
//       <main id="resume" className="">
//         {children}
//       </main>
//       <footer id="footer" className="sections-yframe grow">
//         <section className="sections-xframe grow"></section>
//       </footer>
//     </div>
//   );
// }

import type { Metadata } from "next";
import "@/app/globals.css";
import "./resume.css";
import { Space_Grotesk, Space_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin", "latin-ext"],
  style: "normal",
  variable: "--font-space-grotesk",
});

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin", "latin-ext"],
  style: "normal",
  variable: "--font-space-mono",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${spaceMono.variable}`}
    >
      <body id="body" className="flex flex-col">
        <header>
          <section className="sections-yframe border-y h-12">
            <section className="sections-xframe h-full">
            </section>
          </section>
        </header>
        <main>
          {children}
        </main>
        {/* 下行为填满剩余空间的占位符，为配合上下样式不需要套yframe */}
        <section className="sections-xframe grow"></section>
        <footer>
          <section className="sections-yframe border-y h-12">
            <section className="sections-xframe h-full">
            </section>
          </section>
        </footer>
      </body>
    </html>
  );
}